[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mipview"
version = "0.5.6"
description = "A lightweight Linux-first NIfTI viewer for patch-based inspection workflows."
readme = "README.md"
requires-python = ">=3.11"
license = { text = "Apache-2.0" }
authors = [
  { name = "Marshall Xu" }
]
dependencies = [
  "PySide6>=6.6",
  "nibabel>=5.2",
  "numpy>=1.26",
  "scikit-image>=0.23",
  "vispy>=0.16",
  "PyOpenGL>=3.1.7"
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0"
]

[project.scripts]
mipview = "mipview.main:main"
mipview-ctl = "mipview.control.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
